# Generated by Django 4.0.4 on 2022-05-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.FilePathField(path='/static/img'),
        ),
    ]
