# Generated by Django 4.0.4 on 2022-05-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_album_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='album',
            name='released',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
