# Generated by Django 4.0.4 on 2022-05-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_rename_created_at_album_created_alter_album_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.FilePathField(path='/albums/static/img'),
        ),
    ]
