# Generated by Django 4.0.4 on 2022-05-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_alter_album_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.FilePathField(path='/Users/gerardoayes/Documents/Momentum/Homework/Phase2/django-music-Dito121/albums/static/img/'),
        ),
    ]
